version: '3.3'
services:

  web:
    build:
      context: docker/web
      dockerfile: Dockerfile
    user: root
    volumes:
      - .:/code/
    ports:
      - "8080:8080"
    environment:
      DJANGO_SETTINGS_MODULE: yetAnotherDudeApp.settings
    command: python manage.py runserver 0.0.0.0:8080
    restart: unless-stopped
