version: '3'

services:
  web:
    build:
      context: docker/web
      dockerfile: Dockerfile
    volumes:
      - .:/code/
    ports:
      - "8080:8080"
    command: python manage.py runserver 0.0.0.0:8080
