# Generated by Django 2.0.6 on 2018-06-16 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issueTracker', '0002_auto_20180616_1247'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueSummary',
            fields=[
            ],
            options={
                'verbose_name': 'Issue Summary',
                'verbose_name_plural': 'Issue Summary',
                'proxy': True,
                'indexes': [],
            },
            bases=('issueTracker.issue',),
        ),
    ]
